// GENERATED FILE -- reproduces AppCMakeGenerator.cpp:358-410's real
// emission loop (verified against vixcpp/cli source, this session) for a
// project named "myapp" with two enabled app modules: auth, db.
// Do not edit this file directly.

#include "app_generated.hpp"
#include <vix/executor/RuntimeExecutor.hpp>

#include <utility>

#include <auth/AuthModule.hpp>
#include <db/DbModule.hpp>

namespace vix::app_generated
{
  void register_app_modules(vix::App &app)
  {
    (void)app;

    myapp::auth::AuthModule::register_routes(app);
    myapp::db::DbModule::register_routes(app);
  }
}
