#!/usr/bin/env python3
# Reads sonar_lin_train.c's stdout (already captured in sonar_lin_train.out),
# quantizes each fold's float perceptron weights to int8 (scale so
# max|w over the 60 feature weights| = 127, bias scaled the same way but kept
# as int32_t -- it's an add, not a per-input multiply, so it has no hardware
# reason to be squeezed into 8 bits), and emits:
#   sonar_lin_params.h   -- one lin::CellOf<int32_t,...> type alias per fold
#   sonar_lin_vectors.h  -- that fold's held-out rows (u8 features + label)
# Generated, not hand-written, per the task's own requirement.
import sys, re

def main():
    with open("sonar_lin_train.out") as f:
        lines = f.read().splitlines()

    folds = []
    i = 0
    rows_total = int(lines[0].split("=")[1]); i = 1
    while i < len(lines):
        m = re.match(r"FOLD (\d+) ntr=(\d+) nte=(\d+)", lines[i]); i += 1
        fold, ntr, nte = int(m.group(1)), int(m.group(2)), int(m.group(3))
        train_acc = float(lines[i].split()[1]); i += 1
        test_acc  = float(lines[i].split()[1]); i += 1
        W = [float(x) for x in lines[i].split()[1:]]; i += 1
        assert len(W) == 61
        rows = []
        for _ in range(nte):
            vals = [int(x) for x in lines[i].split()[1:]]; i += 1
            assert len(vals) == 62  # 60 features + true label + float model's own prediction
            rows.append(vals)
        folds.append(dict(fold=fold, ntr=ntr, nte=nte, train_acc=train_acc,
                           test_acc=test_acc, W=W, rows=rows))

    params = ["#pragma once", "// generated by gen_lin_sonar.py from sonar_lin_train.out -- do not hand-edit", '#include "linCell.h"', ""]
    vectors = ["#pragma once", "// generated by gen_lin_sonar.py from sonar_lin_train.out -- do not hand-edit",
                "#include <stdint.h>", "#ifndef SONAR_LIN_VEC_ATTR", "#define SONAR_LIN_VEC_ATTR", "#endif", ""]

    for fd in folds:
        n = fd["fold"]
        w = fd["W"][:60]; bias = fd["W"][60]
        # sonar_lin_train.c's perceptron trains on NORMALIZED inputs (Q[j]/255),
        # but the int model multiplies the RAW u8 input directly (no hardware
        # division). float_output = sum(w_j*x_j/255) + bias; multiplying the
        # whole expression by 255*scale gives an integer-computable quantity
        # with the same sign: sum((scale*w_j)*x_j) + (255*scale*bias). Missing
        # that 255x on the bias (relative to the weights) first cut int8 test
        # accuracy to ~60% agreement with the float model -- looked like a
        # quantization failure, was actually this scale mismatch.
        scale = 127.0 / max(abs(x) for x in w)
        wq = [round(x*scale) for x in w]
        wq = [max(-127, min(127, x)) for x in wq]  # defensive clamp
        bq = round(255*scale*bias)

        # int16 product, int32 accumulator: each term's multiply fits a single
        # native 16x16 multiply (max |w|*|x| = 127*255 = 32385 < int16_t max),
        # only the running sum needs the wider type. This is the recommended
        # form -- see the README for the measured AVR cost of the naive
        # int32-product alternative kept below for direct comparison.
        terms16 = ", ".join(f"lin::InOf<int32_t,int16_t,{j},{wq[j]}>" for j in range(60))
        params.append(f"// fold {n}: float train {fd['train_acc']:.2f} test {fd['test_acc']:.2f}, scale={scale:.6g}")
        params.append(f"using SonarLinFold{n} = lin::CellOf<int32_t, {bq}, lin::SignOf<int32_t>, {terms16}>;")
        # naive form: product computed at the full int32_t accumulator width,
        # kept only as a comparison point (README).
        terms32 = ", ".join(f"lin::InOf<int32_t,int32_t,{j},{wq[j]}>" for j in range(60))
        params.append(f"using SonarLinFold{n}Wide = lin::CellOf<int32_t, {bq}, lin::SignOf<int32_t>, {terms32}>;")
        params.append(f"#define SONAR_LIN_FOLD{n}_TRAIN_ACC {fd['train_acc']:.5f}")
        params.append(f"#define SONAR_LIN_FOLD{n}_TEST_ACC {fd['test_acc']:.5f}")
        params.append("")

        vectors.append(f"// row = {{60 quantized features, true label, float model's own prediction}}")
        vectors.append(f"#define SONAR_LIN_FOLD{n}_NVEC {fd['nte']}")
        vectors.append(f"static const uint8_t SONAR_LIN_FOLD{n}_VEC[{fd['nte']}][62] SONAR_LIN_VEC_ATTR = {{")
        for r in fd["rows"]:
            vectors.append(" {" + ",".join(str(x) for x in r) + "},")
        vectors.append("};")
        vectors.append("")

    with open("sonar_lin_params.h", "w") as f: f.write("\n".join(params) + "\n")
    with open("sonar_lin_vectors.h", "w") as f: f.write("\n".join(vectors) + "\n")
    print(f"wrote sonar_lin_params.h and sonar_lin_vectors.h for {len(folds)} folds, {rows_total} total rows")

if __name__ == "__main__":
    main()
