#pragma once
// The trained Banknote classifier of the running example, as a TYPE: one wave cell of four graded inputs. The trained parameters
// (wave_params.h, generated by train/bn2x.c: fold 1) are template arguments; there is no table. Its inputs are the four fields of one
// slot, named as the dataset names them; a Wave reads its field by name.
#include "waveCell.h"
#include "wave_params.h"

struct BanknoteTag {};
struct BanknoteIn { uint8_t variance, skewness, curtosis, entropy; };
using BanknoteState = hapi::APIOf<hapi::SlotApi, hapi::Slot<BanknoteTag,BanknoteIn>>::Res;
using Variance = snet::Field<BanknoteTag,&BanknoteIn::variance>;
using Skewness = snet::Field<BanknoteTag,&BanknoteIn::skewness>;
using Curtosis = snet::Field<BanknoteTag,&BanknoteIn::curtosis>;
using Entropy  = snet::Field<BanknoteTag,&BanknoteIn::entropy>;
inline BanknoteState banknote(const BanknoteIn& in) { return BanknoteState{{}, {in}}; }              // banknote({variance, skewness, curtosis, entropy})

using BanknoteNet=wave::Cell<WAVE_K,
  wave::Threshold,
  wave::Wave<Variance,WAVE_VARIANCE_N,WAVE_VARIANCE_S,WAVE_VARIANCE_P,WAVE_VARIANCE_M>,
  wave::Wave<Skewness,WAVE_SKEWNESS_N,WAVE_SKEWNESS_S,WAVE_SKEWNESS_P,WAVE_SKEWNESS_M>,
  wave::Wave<Curtosis,WAVE_CURTOSIS_N,WAVE_CURTOSIS_S,WAVE_CURTOSIS_P,WAVE_CURTOSIS_M>,
  wave::Wave<Entropy,WAVE_ENTROPY_N,WAVE_ENTROPY_S,WAVE_ENTROPY_P,WAVE_ENTROPY_M>
>;
