#pragma once
// The trained Banknote classifier of the running example, as a TYPE: one wave cell of four graded inputs. The trained parameters
// (wave_params.h, generated by train/bn2x.c: fold 1) are template arguments; there is no table and no state.
#include "waveCell.h"
#include "wave_params.h"
using BanknoteNet=wave::Cell<WAVE_K,
  wave::Threshold,
  wave::Wave<0,WAVE_F0_N,WAVE_F0_S,WAVE_F0_P,WAVE_F0_M>,
  wave::Wave<1,WAVE_F1_N,WAVE_F1_S,WAVE_F1_P,WAVE_F1_M>,
  wave::Wave<2,WAVE_F2_N,WAVE_F2_S,WAVE_F2_P,WAVE_F2_M>,
  wave::Wave<3,WAVE_F3_N,WAVE_F3_S,WAVE_F3_P,WAVE_F3_M>
>;
