// generated by bn2.c, Banknote 5-fold CV, fold 1 (seed 42): train 99.64% test 100.00%
#pragma once
#define WAVE_K 175
#define WAVE_VARIANCE_N 0
#define WAVE_VARIANCE_S -2
#define WAVE_VARIANCE_P 110
#define WAVE_VARIANCE_M 0xba
#define WAVE_SKEWNESS_N 0
#define WAVE_SKEWNESS_S -2
#define WAVE_SKEWNESS_P 80
#define WAVE_SKEWNESS_M 0xbf
#define WAVE_CURTOSIS_N 0
#define WAVE_CURTOSIS_S -2
#define WAVE_CURTOSIS_P 0
#define WAVE_CURTOSIS_M 0x3f
#define WAVE_ENTROPY_N 0
#define WAVE_ENTROPY_S -7
#define WAVE_ENTROPY_P 0
#define WAVE_ENTROPY_M 0x01
// quantization q=round((x-min)/(max-min)*255), clamped; in the order of the features named above
static const double WAVE_MIN[4]={-7.0420999999999996,-13.773099999999999,-5.2861000000000002,-8.5481999999999996};
static const double WAVE_MAX[4]={6.8247999999999998,12.7302,17.927399999999999,2.1625000000000001};
