#!/usr/bin/env python3
"""make.py -- the two Compiler Explorer sources for static_net's Banknote wave4 cell, assembled from the real files.

    wave4_od.cpp     waveCell.h as translate.py writes it, with its ':' source (round2/src/waveCell.h) as a leading comment
    wave4_apiof.cpp  waveCell.h as examples/static_net/include/waveCell.h has it (Cell = hapi::APIOf<...>)

Both are self-contained apart from one #include of single/hapi.h by raw GitHub URL, pinned to a commit (HAPI_SHA),
and otherwise identical: staticNet.h, wave_params.h, net.h (the trained cell) and the entry point wave4() of
compare_emlearn/bnc_wave.h, inlined in that order. Re-run after changing any of them; verify.sh checks the result.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
OD = os.path.dirname(HERE)
R = os.path.dirname(os.path.dirname(OD))
SN = os.path.join(R, "examples", "static_net")
HAPI_SHA = "3b0c466ca5a6870a0747abc8133fd64743c333b7"   # the commit that added single/hapi.h
URL = f"https://raw.githubusercontent.com/InternetOfPins/HAPI/{HAPI_SHA}/single/hapi.h"


def body(path, drop=()):
    """a header's text without #pragma once and without the includes the single source already provides."""
    out = []
    for line in open(path):
        if re.match(r"\s*#\s*pragma\s+once", line):
            continue
        m = re.match(r'\s*#\s*include\s*[<"]([^>"]+)[>"]', line)
        if m and m.group(1) in drop:
            continue
        out.append(line)
    return "".join(out).strip("\n") + "\n"


def section(title, text):
    return f"\n// ======== {title} ========\n{text}"


def source(which):
    rel = lambda p: os.path.relpath(p, R)
    local = ("hapi/hapi.h", "staticNet.h", "waveCell.h", "wave_params.h")
    if which == "od":
        src = os.path.join(OD, "round2", "src", "waveCell.h")
        cell = os.path.join(OD, "round2", "out", "include", "waveCell.h")
        head = ["// Banknote wave4 (static_net), waveCell.h written with Open Derivation (':' late derivation), as translated.",
                "// The ':' source, " + rel(src) + ", which .RnD/openDerivation/translate.py lowers to the waveCell.h below:",
                "//"] + ["//   " + l.rstrip() for l in open(src).read().splitlines()] + ["//"]
    else:
        cell = os.path.join(SN, "include", "waveCell.h")
        head = ["// Banknote wave4 (static_net), waveCell.h as written by hand: Cell = hapi::APIOf<API,OO...,Bias<k>>."]
    head += ["// Generated by .RnD/openDerivation/godbolt/make.py (HAPI " + HAPI_SHA[:7] + "). Compile for AVR with",
             "// -std=c++17 -Os -mmcu=atmega328p; wave4() is the function to read (see README.md)."]
    parts = ["\n".join(head) + "\n",
             f"#include <{URL}>\n",
             section(rel(os.path.join(SN, "include", "staticNet.h")), body(os.path.join(SN, "include", "staticNet.h"), local)),
             section(rel(cell) + ("  (translated)" if which == "od" else ""), body(cell, local)),
             section(rel(os.path.join(SN, "models", "banknote", "wave_params.h")), body(os.path.join(SN, "models", "banknote", "wave_params.h"), local)),
             section(rel(os.path.join(SN, "models", "banknote", "net.h")), body(os.path.join(SN, "models", "banknote", "net.h"), local)),
             section("entry point (compare_emlearn/bnc_wave.h's bnc_predict)",
                     "bool wave4(const uint8_t* x) {wave::Features<4> f{{x[0],x[1],x[2],x[3]}}; return BanknoteNet::proc(f);}\n")]
    return "".join(parts)


for which, name in (("od", "wave4_od.cpp"), ("apiof", "wave4_apiof.cpp")):
    with open(os.path.join(HERE, name), "w") as f:
        f.write(source(which))
    print("wrote", name)
