// Banknote wave4 (static_net), waveCell.h written with Open Derivation (':' late derivation), as translated.
// The ':' source, .RnD/openDerivation/round2/src/waveCell.h, which .RnD/openDerivation/translate.py lowers to the waveCell.h below:
//
//   #pragma once
//   // waveCell.h — conditional-free, multiply-free phase cell components (HAPI Part<O> style)
//   // one engine for snet::Net; the u8 cast of any source lives here, not in the composition layer
//   #include "staticNet.h"
//   #include <stdint.h>
//   
//   namespace wave {
//     using u8=uint8_t; // not µ: UTF-8 identifiers need GCC>=10, avr-gcc 7.3 rejects them
//     using snet::Net; using snet::Slot; using snet::Ref;
//   
//     struct API {
//       template<typename I> SNET_INLINE static constexpr u8 proc(const I&) {return 0;}
//       template<typename I> SNET_INLINE static constexpr void update(I&) {}
//     };
//   
//     // global phase offset
//     template<u8 k>
//     struct Bias {
//       template<typename I> SNET_INLINE static constexpr u8 proc(const I& in) {return u8(k+super::proc(in));}
//     };
//   
//     // graded source: optional NOT, shift (s<0 right, s>0 left), phase add, bit-mask readout
//     template<typename Src,bool n,int s,u8 p,u8 m>
//     struct WaveOf {
//       static constexpr u8 inv(u8 x) {return n?u8(~x):x;}
//       static constexpr u8 shf(u8 x) {return s>=0?u8(x<<s):u8(x>>(-s));}
//       template<typename I> SNET_INLINE static constexpr u8 proc(const I& in)
//         {return u8(u8(u8(shf(inv(u8(Src::get(in))))+p)&m)+super::proc(in));}
//     };
//     template<size_t i,bool n,int s,u8 p,u8 m> using Wave=WaveOf<Slot<i>,n,s,p,m>;
//     template<size_t j,bool n,int s,u8 p,u8 m> using RefWave=WaveOf<Ref<j>,n,s,p,m>;
//   
//     // readout of bit 7 (phase < half)
//     struct Threshold {
//       template<typename I> SNET_INLINE static constexpr bool proc(const I& in) {return super::proc(in)<128;}
//     };
//   
//     // writes the running proc() value at this point into state slot i, then chains to the next Store
//     template<size_t i>
//     struct Store {
//       template<typename I> SNET_INLINE static constexpr void update(I& in) {
//         in.template set<i>(super::proc(in));
//         super::update(in);
//       }
//     };
//   
//     template<u8 k,typename... OO> struct Cell : (OO : ... : Bias<k> : final API) {};
//   
//     // input state passed by value/reference, no global reads (CSE-eligible)
//     template<size_t N> struct Features {
//       u8 v[N];
//       template<size_t i> constexpr u8 get() const {return v[i];}
//       template<size_t i> constexpr void set(u8 x) {v[i]=x;}
//       constexpr const u8* data() const {return v;}
//     };
//   }
//
// Generated by .RnD/openDerivation/godbolt/make.py (HAPI 3b0c466). Compile for AVR with
// -std=c++17 -Os -mmcu=atmega328p; wave4() is the function to read (see README.md).
#include <https://raw.githubusercontent.com/InternetOfPins/HAPI/3b0c466ca5a6870a0747abc8133fd64743c333b7/single/hapi.h>

// ======== examples/static_net/include/staticNet.h ========
// staticNet.h — engine-agnostic static network composition
// Net = typelist of cell types (no instances). State is the only runtime data.
// Cells are any type with `static proc(in)` (and optionally `static update(in)`),
// pure over the state view they are given. Value types flow from each cell's proc.
#include <stddef.h>

#ifndef SNET_INLINE
  // avr-gcc 7.3 -Os declines to inline multiply-called proc chains (measured, see README); force it
  #define SNET_INLINE [[gnu::always_inline]]
#endif

namespace snet {
  // state view: net and current cell index as phantom types, holds only a reference
  template<typename N,typename S,size_t k> struct Ctx {
    using Net=N;
    static constexpr size_t cur=k;
    S& s;
    template<size_t j> SNET_INLINE constexpr Ctx<N,S,j> at() const {return {s};}
    template<size_t i> SNET_INLINE constexpr decltype(auto) get() const {return s.template get<i>();}
    template<size_t i,typename V> SNET_INLINE constexpr void set(V x) const {s.template set<i>(x);}
    SNET_INLINE constexpr auto data() const {return s.data();}     // the raw slot bytes, for parts that iterate over them (roll.h)
  };

  // in-place reference to cell j of the enclosing net (same pass, pure, CSE-foldable)
  template<size_t j> struct Ref {
    template<typename I> SNET_INLINE static constexpr auto get(const I& in) {
      static_assert(j<I::cur,"snet::Ref<j>: in-place reference must point to a lower net index; a cycle needs a register (Slot<i> + Store<i>)");
      return I::Net::template Cell<j>::proc(in.template at<j>());
    }
  };

  // state slot i: a true input edge, or a register written by a Store<i>
  template<size_t i> struct Slot {
    template<typename I> SNET_INLINE static constexpr auto get(const I& in) {return in.template get<i>();}
  };

  template<typename... CC> struct Net {
    using Cells=hapi::Chain<CC...>;
    template<size_t j> using Cell=typename Cells::template Drop<j>::Head;
    template<size_t j,typename S> SNET_INLINE static constexpr auto proc(S& s)
      {return Cell<j>::proc(Ctx<Net,S,j>{s});}
    template<size_t j,typename S> SNET_INLINE static constexpr void update(S& s)
      {Ctx<Net,S,j> c{s}; Cell<j>::update(c);}
  };
}

// What a Net holds, for HAPI's structural walks: its cells, in order. Queries, Filter/Map/Partition and FindFirst
// open it; rules() are not run inside it (nothing nests a Net today). The cells stay whole, a cell being an APIOf
// (a leaf for those walks), which is why refid.h matches them with FromTypes.
namespace hapi {
  template<typename... CC>
  struct Expand<snet::Net<CC...>> : Expansion<Chain<CC...>,true,true,false,true> {};
}

// ======== .RnD/openDerivation/round2/out/include/waveCell.h  (translated) ========
// waveCell.h — conditional-free, multiply-free phase cell components (HAPI Part<O> style)
// one engine for snet::Net; the u8 cast of any source lives here, not in the composition layer
#include <stdint.h>

namespace wave {
  using u8=uint8_t; // not µ: UTF-8 identifiers need GCC>=10, avr-gcc 7.3 rejects them
  using snet::Net; using snet::Slot; using snet::Ref;

  struct API {
    template<typename I> SNET_INLINE static constexpr u8 proc(const I&) {return 0;}
    template<typename I> SNET_INLINE static constexpr void update(I&) {}
  };

  // global phase offset
  template<u8 k>
  struct Bias {template<typename O> struct Part:O {
    using Base=O; using Base::Base;
    template<typename I> SNET_INLINE static constexpr u8 proc(const I& in) {return u8(k+Base::proc(in));}
  };};

  // graded source: optional NOT, shift (s<0 right, s>0 left), phase add, bit-mask readout
  template<typename Src,bool n,int s,u8 p,u8 m>
  struct WaveOf {template<typename O> struct Part:O {
    using Base=O; using Base::Base;
    static constexpr u8 inv(u8 x) {return n?u8(~x):x;}
    static constexpr u8 shf(u8 x) {return s>=0?u8(x<<s):u8(x>>(-s));}
    template<typename I> SNET_INLINE static constexpr u8 proc(const I& in)
      {return u8(u8(u8(shf(inv(u8(Src::get(in))))+p)&m)+Base::proc(in));}
  };};
  template<size_t i,bool n,int s,u8 p,u8 m> using Wave=WaveOf<Slot<i>,n,s,p,m>;
  template<size_t j,bool n,int s,u8 p,u8 m> using RefWave=WaveOf<Ref<j>,n,s,p,m>;

  // readout of bit 7 (phase < half)
  struct Threshold {template<typename O> struct Part:O {
    using Base=O; using Base::Base;
    template<typename I> SNET_INLINE static constexpr bool proc(const I& in) {return Base::proc(in)<128;}
  };};

  // writes the running proc() value at this point into state slot i, then chains to the next Store
  template<size_t i>
  struct Store {template<typename O> struct Part:O {
    using Base=O; using Base::Base;
    template<typename I> SNET_INLINE static constexpr void update(I& in) {
      in.template set<i>(Base::proc(in));
      Base::update(in);
    }
  };};

  template<u8 k,typename... OO> struct Cell : hapi::APIOf<API,OO...,Bias<k>> {using Base=hapi::APIOf<API,OO...,Bias<k>>; using Base::Base; static_assert(hapi::Distinct<hapi::Chain<OO...,Bias<k>,API>>, "duplicate layer in Cell");}; template<u8 k,typename... OO> using Cell_APIOf=hapi::APIOf<API,OO...,Bias<k>>; } namespace hapi { template<auto k,typename... OO> struct Expand< ::wave::Cell<k,OO...>> : Expand< ::wave::Cell_APIOf<k,OO...>> {}; template<auto k,typename... OO> struct HasOwnRules< ::wave::Cell<k,OO...>> : HasOwnRules< ::wave::Cell_APIOf<k,OO...>> {}; } namespace wave {

  // input state passed by value/reference, no global reads (CSE-eligible)
  template<size_t N> struct Features {
    u8 v[N];
    template<size_t i> constexpr u8 get() const {return v[i];}
    template<size_t i> constexpr void set(u8 x) {v[i]=x;}
    constexpr const u8* data() const {return v;}
  };
}

// ======== examples/static_net/models/banknote/wave_params.h ========
// generated by bn2.c, Banknote 5-fold CV, fold 1 (seed 42): train 99.64% test 100.00%
#define WAVE_K 175
#define WAVE_F0_N 0
#define WAVE_F0_S -2
#define WAVE_F0_P 110
#define WAVE_F0_M 0xba
#define WAVE_F1_N 0
#define WAVE_F1_S -2
#define WAVE_F1_P 80
#define WAVE_F1_M 0xbf
#define WAVE_F2_N 0
#define WAVE_F2_S -2
#define WAVE_F2_P 0
#define WAVE_F2_M 0x3f
#define WAVE_F3_N 0
#define WAVE_F3_S -7
#define WAVE_F3_P 0
#define WAVE_F3_M 0x01
// quantization q=round((x-min)/(max-min)*255), clamped
static const double WAVE_MIN[4]={-7.0420999999999996,-13.773099999999999,-5.2861000000000002,-8.5481999999999996};
static const double WAVE_MAX[4]={6.8247999999999998,12.7302,17.927399999999999,2.1625000000000001};

// ======== examples/static_net/models/banknote/net.h ========
// The trained Banknote classifier of the running example, as a TYPE: one wave cell of four graded inputs. The trained parameters
// (wave_params.h, generated by train/bn2x.c: fold 1) are template arguments; there is no table and no state.
using BanknoteNet=wave::Cell<WAVE_K,
  wave::Threshold,
  wave::Wave<0,WAVE_F0_N,WAVE_F0_S,WAVE_F0_P,WAVE_F0_M>,
  wave::Wave<1,WAVE_F1_N,WAVE_F1_S,WAVE_F1_P,WAVE_F1_M>,
  wave::Wave<2,WAVE_F2_N,WAVE_F2_S,WAVE_F2_P,WAVE_F2_M>,
  wave::Wave<3,WAVE_F3_N,WAVE_F3_S,WAVE_F3_P,WAVE_F3_M>
>;

// ======== entry point (compare_emlearn/bnc_wave.h's bnc_predict) ========
bool wave4(const uint8_t* x) {wave::Features<4> f{{x[0],x[1],x[2],x[3]}}; return BanknoteNet::proc(f);}
