#!/usr/bin/env python3
# Round 4 -- parse hello_world_float.tflite and emit hello_world_weights.h
# (the FullyConnected weights/biases, all layers), plus print the architecture.
# Reads the flatbuffer with the tiny `tflite` package -- no TensorFlow.
#   .venv/bin/python tools/extract_weights.py
import sys, os, numpy as np, tflite

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MODEL = os.path.join(ROOT, "models", "hello_world_float.tflite")
OUT = os.path.join(ROOT, "hello_world_weights.h")

buf = open(MODEL, "rb").read()
model = tflite.Model.GetRootAsModel(buf, 0)
g = model.Subgraphs(0)

def tensor_np(t_idx):
    t = g.Tensors(t_idx)
    b_idx = t.Buffer()
    raw = model.Buffers(b_idx).DataAsNumpy()
    shape = [t.Shape(i) for i in range(t.ShapeLength())]
    if isinstance(raw, int):        # empty buffer
        return None, shape, t.Type()
    return np.frombuffer(raw.tobytes(), dtype=np.float32).reshape(shape), shape, t.Type()

BUILTIN = {v: k for k, v in tflite.BuiltinOperator.__dict__.items() if isinstance(v, int)}

layers = []          # (in_size, out_size, W[out][in], b[out], relu?)
print("== hello_world_float.tflite ==")
print("operators:", g.OperatorsLength(), " tensors:", g.TensorsLength())
for i in range(g.OperatorsLength()):
    op = g.Operators(i)
    oc = model.OperatorCodes(op.OpcodeIndex())
    code = oc.BuiltinCode()
    name = BUILTIN.get(code, str(code))
    ins = [op.Inputs(j) for j in range(op.InputsLength())]
    outs = [op.Outputs(j) for j in range(op.OutputsLength())]
    print(f"  op{i}: {name}  inputs={ins} outputs={outs}")
    if name == "FULLY_CONNECTED":
        W, wshape, _ = tensor_np(ins[1])       # [out, in]
        B, bshape, _ = tensor_np(ins[2])       # [out]
        # fused activation
        opt = op.BuiltinOptions()
        act = 0
        if opt is not None:
            fco = tflite.FullyConnectedOptions()
            fco.Init(opt.Bytes, opt.Pos)
            act = fco.FusedActivationFunction()
        relu = (act == tflite.ActivationFunctionType.RELU)
        print(f"       W{wshape} B{bshape} act={act} relu={relu}")
        layers.append((wshape[1], wshape[0], W, B, relu))

def cfloat(x):
    s = f"{float(x):.9g}"
    if "." not in s and "e" not in s and "E" not in s and "inf" not in s and "nan" not in s:
        s += ".0"
    return s + "f"

def carr(a):
    return ", ".join(cfloat(x) for x in np.asarray(a).ravel())

with open(OUT, "w") as f:
    f.write("// GENERATED by tools/extract_weights.py from models/hello_world_float.tflite\n")
    f.write("// TFLM hello_world sine regressor. Do not hand-edit.\n#pragma once\n\n")
    f.write(f"#define HW_NLAYERS {len(layers)}\n")
    dims = [layers[0][0]] + [l[1] for l in layers]
    f.write("// layer dims: " + " -> ".join(map(str, dims)) + "\n")
    f.write("static constexpr int HW_DIMS[HW_NLAYERS+1] = {" + ", ".join(map(str, dims)) + "};\n")
    f.write("static constexpr bool HW_RELU[HW_NLAYERS] = {"
            + ", ".join("true" if l[4] else "false" for l in layers) + "};\n\n")
    for i, (isz, osz, W, B, relu) in enumerate(layers):
        f.write(f"// layer {i}: FC {isz} -> {osz}{' + ReLU' if relu else ''}\n")
        f.write(f"static constexpr float HW_W{i}[{osz*isz}] = {{ {carr(W)} }};   // [out][in], row-major\n")
        f.write(f"static constexpr float HW_B{i}[{osz}] = {{ {carr(B)} }};\n\n")

print("\nwrote", OUT, "  dims:", dims)
