// GENERATED FILE -- reproduces AppCMakeGenerator.cpp's real emitted shape
// (verified against vixcpp/cli source, this session) for a project named
// "myapp" with two enabled app modules: auth, db.
// Do not edit this file directly.

#include <memory>

namespace vix
{
  class App;
}

namespace vix::app_generated
{
  void register_app_modules(vix::App &app);
}
