// generated by gen_models.py: lin4 = fold 1's float perceptron quantized (scale 4.97084): int8 weights, int32 accumulator, int16 product
#include "waveCell.h"
#include "linCell.h"
using BncLin = lin::CellOf<int32_t,39294,lin::SignOf<int32_t>,lin::InOf<int32_t,int16_t,0,-112>,lin::InOf<int32_t,int16_t,1,-113>,lin::InOf<int32_t,int16_t,2,-127>,lin::InOf<int32_t,int16_t,3,-1>>;
__attribute__((noinline)) bool bnc_predict(const uint8_t* x){ wave::Features<4> f{{x[0],x[1],x[2],x[3]}}; return snet::Net<BncLin>::proc<0>(f); }
