// The device half of the Banknote comparison. One program per model, all built and measured the same way (run.sh): fold 1's held-out rows
// (the rows of ../models/banknote/wave_vectors.h, in PROGMEM) go through bnc_predict() one at a time, each timed with Timer1 (../measure/harness.h, as everywhere in
// measure/), and the program reports, over UART: how many it got right, and the min / max / sum of cycles over the rows. Models with a
// data-dependent path (trees) therefore show min < max; the cells (wave4, lin4, table4) do not.
// The model header defines bool bnc_predict(const uint8_t* x) (4 quantized bytes -> class), out of line like every measure/ target.
#include "harness.h"
#include <avr/pgmspace.h>
#include "bnc_rows.h"                    // generated by gen_models.py: BNC_N, BNC_X[BNC_N][4], BNC_Y[BNC_N]
#ifndef BNC_NAME
  #define BNC_NAME "null"
#endif
bool bnc_predict(const uint8_t* x);
static void uputl(uint32_t v){ char b[11]; int i=0; do{b[i++]='0'+v%10; v/=10;}while(v); while(i) uputc(b[--i]); }
int main(){ uinit();
  uint16_t e0,e1; TCNT1=0; e0=TCNT1; e1=TCNT1; const uint16_t over=e1-e0;         // the cost of reading the counter twice, as MEASURE does
  uint32_t sum=0; uint16_t mn=0xFFFF, mx=0, ok=0;
  cli();
  for(uint16_t r=0;r<BNC_N;r++){
    uint8_t x[4]; for(uint8_t i=0;i<4;i++) x[i]=pgm_read_byte(&BNC_X[r][i]);
    uint16_t t0,t1; TCNT1=0; t0=TCNT1; bool y=bnc_predict(x); KEEP(y); t1=TCNT1;
    uint16_t c=(t1-t0)-over; sum+=c; if(c<mn) mn=c; if(c>mx) mx=c; ok+=(y==(bool)pgm_read_byte(&BNC_Y[r]));
  }
  uputs(BNC_NAME); uputs(": n="); uputu(BNC_N); uputs(" ok="); uputu(ok); uputs(" min="); uputu(mn); uputs(" max="); uputu(mx); uputs(" sum="); uputl(sum);
  done(); }
