// generated by gen_models.py: table4 = the weights of bnc_lin.h in a PROGMEM table and a loop
#include <avr/pgmspace.h>
#include <stdint.h>
static const int8_t BNC_W[4] PROGMEM = {-112,-113,-127,-1};
__attribute__((noinline)) bool bnc_predict(const uint8_t* x){ int32_t a=39294; for(uint8_t i=0;i<4;i++) a+=int16_t((int8_t)pgm_read_byte(&BNC_W[i]))*int16_t(x[i]); return a>0; }
