// generated by gen_models.py: lin4 = fold 1's float perceptron quantized (scale 4.97084): int8 weights, int32 accumulator, int16 product
#include "waveCell.h"
#include "linCell.h"
#include "net.h"
using BncLin = lin::CellOf<int32_t,39294,lin::SignOf<int32_t>,lin::InOf<int32_t,int16_t,Variance,-112>,lin::InOf<int32_t,int16_t,Skewness,-113>,lin::InOf<int32_t,int16_t,Curtosis,-127>,lin::InOf<int32_t,int16_t,Entropy,-1>>;
__attribute__((noinline)) bool bnc_predict(const uint8_t* x){ BanknoteState f = banknote({x[BNC_COL_VARIANCE],x[BNC_COL_SKEWNESS],x[BNC_COL_CURTOSIS],x[BNC_COL_ENTROPY]}); return snet::Net<BncLin>::proc<0>(f); }
