#!/usr/bin/env python3
"""Generates everything the Banknote comparison needs, from bn2x.c's fold export.

    gen_models.py [dir with fold0.csv..fold4.csv, perceptron.csv, bn2x.out; default data/]     (needs numpy, scikit-learn, emlearn; see README.md)

The task is the Banknote task of the running example (../train/bn2x.c): UCI Banknote, 4 features quantized to 8 bits with each training fold's min/max, 5-fold CV with
the shuffle of bn2.c (seed 42). bn2x.c is bn2.c plus an export of every fold's quantized train and test rows and of the float perceptron;
its training is untouched, so its wave parameters for fold 1 are the committed ../models/banknote/wave_params.h (checked below against wave_vectors.h).

Every model is trained on each fold's training rows and scored on that fold's held-out rows, so all numbers are on the same folds:
  wave4    the masked-wave cell of bn2.c (accuracies parsed from bn2x.out; fold 1 is the cell on the device)
  lin4     the float perceptron of bn2.c quantized like the Sonar cells (int8 weights, int32 accumulator, int16 product); table4: same weights, a loop
  tree     emlearn 0.23.2 inline decision tree (sklearn DecisionTreeClassifier), features as float (emlearn's default) and as uint8_t (its dtype option)
  mlp      emlearn eml_net (sklearn MLPClassifier, one hidden layer, relu, best of 5 restarts on the training rows), float; the 1/255 input scaling is folded into the first layer, so the
           device feeds the raw byte values as floats. Accuracy is that of emlearn's C code, run on the host, not of sklearn.
Writes, next to this file: bnc_rows.h (fold 1's held-out rows for the device), bnc_lin.h, bnc_table.h, models/*.h (emlearn code + bnc_predict()),
results.json (per-model, per-fold accuracy and the parameters that size the model)."""
import csv, json, os, re, sys, warnings
import numpy as np
import emlearn
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

warnings.filterwarnings('ignore')
np.seterr(all='ignore')          # emlearn turns numpy's floating-point errors into exceptions; a harmless underflow in adam must not stop a fit
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, 'data')
NFOLD = int(os.environ.get('BNC_FOLDS', '5'))          # 5; fewer only for a smoke test while the export is unfinished
TREE_DEPTHS = [2, 3, 4, 5, 6, 8, 10]
MLP_HIDDEN = [2, 4, 8, 16]


def load_fold(f):
    tr, te = [], []
    for r in csv.DictReader(open(os.path.join(SRC, 'fold%d.csv' % f))):
        (tr if r['split'] == 'train' else te).append([int(r[k]) for k in ('q0', 'q1', 'q2', 'q3', 'y')])
    tr, te = np.array(tr), np.array(te)
    return tr[:, :4], tr[:, 4], te[:, :4], te[:, 4]


folds = [load_fold(f) for f in range(NFOLD)]
perc = {int(r['fold']): [float(r[k]) for k in ('w0', 'w1', 'w2', 'w3', 'bias')] for r in csv.DictReader(open(os.path.join(SRC, 'perceptron.csv')))}
results = {'task': 'UCI Banknote, 4 features quantized to 8 bits, 5-fold CV (bn2.c, seed 42)', 'emlearn': emlearn.__version__ if hasattr(emlearn, '__version__') else '0.23.2', 'models': {}}


def record(name, accs, **extra):
    results['models'][name] = dict(test_acc_per_fold=[round(100.0 * a, 2) for a in accs], test_acc_mean=round(100.0 * float(np.mean(accs)), 2),
                                   test_acc_fold1=round(100.0 * accs[1], 2), **extra)


# ---- fold 1's held-out rows for the device; they must be the rows of ../models/banknote/wave_vectors.h
Xtr1, ytr1, Xte1, yte1 = folds[1]
wv = re.findall(r'\{(\d+),(\d+),(\d+),(\d+),(\d+),(\d+)\}', open(os.path.join(HERE, '../models/banknote/wave_vectors.h')).read())
wv = np.array([[int(v) for v in r] for r in wv])
assert wv.shape[0] == len(Xte1) and (wv[:, :4] == Xte1).all() and (wv[:, 4] == yte1).all(), "fold 1 of the export is not the fold of wave_vectors.h"
print('fold 1 held-out rows: %d, identical to ../models/banknote/wave_vectors.h' % len(Xte1))
with open(os.path.join(HERE, 'bnc_rows.h'), 'w') as o:
    o.write('#pragma once\n// generated by gen_models.py: fold 1\'s held-out rows (quantized with fold 1\'s train min/max) and their labels, in flash\n')
    o.write('#include <avr/pgmspace.h>\n#include <stdint.h>\n#define BNC_N %d\n' % len(Xte1))
    o.write('static const uint8_t BNC_X[BNC_N][4] PROGMEM = {\n' + ',\n'.join(' {%d,%d,%d,%d}' % tuple(r) for r in Xte1) + '\n};\n')
    o.write('static const uint8_t BNC_Y[BNC_N] PROGMEM = {' + ','.join(str(v) for v in yte1) + '};\n')

# ---- wave4: bn2x's own printout
wave = [float(m) for m in re.findall(r'masked wave train [\d.]+ test ([\d.]+)', open(os.path.join(SRC, 'bn2x.out')).read())]
assert len(wave) >= NFOLD
wave = wave[:NFOLD]
record('wave4', [w / 100.0 for w in wave], note='masked wave, seeded from frequency-only (bn2.c); fold 1 is ../models/banknote/wave_params.h')

# ---- lin4 / table4: the float perceptron, quantized like gen_lin_sonar.py (the bias is scaled by 255 because the float model sees x/255)
lin_accs, lin1 = [], None
for f in range(NFOLD):
    w, bias = perc[f][:4], perc[f][4]
    scale = 127.0 / max(abs(v) for v in w)
    wq = [max(-127, min(127, round(v * scale))) for v in w]
    bq = round(255 * scale * bias)
    Xte, yte = folds[f][2], folds[f][3]
    a = bq + Xte.astype(np.int64) @ np.array(wq, dtype=np.int64)
    lin_accs.append(float(((a > 0) == yte).mean()))
    if f == 1:
        lin1 = (wq, bq, scale)
record('lin4', lin_accs, weights_fold1=lin1[0], bias_fold1=lin1[1], note='float perceptron of bn2.c quantized: int8 weights, int32 accumulator')
record('table4', lin_accs, note='same weights as lin4, a loop over a PROGMEM table: same answers by construction')
wq, bq, scale = lin1
terms = ','.join('lin::InOf<int32_t,int16_t,%d,%d>' % (i, wq[i]) for i in range(4))
open(os.path.join(HERE, 'bnc_lin.h'), 'w').write(
    '// generated by gen_models.py: lin4 = fold 1\'s float perceptron quantized (scale %.6g): int8 weights, int32 accumulator, int16 product\n'
    '#include "waveCell.h"\n#include "linCell.h"\nusing BncLin = lin::CellOf<int32_t,%d,lin::SignOf<int32_t>,%s>;\n'
    '__attribute__((noinline)) bool bnc_predict(const uint8_t* x){ wave::Features<4> f{{x[0],x[1],x[2],x[3]}}; return snet::Net<BncLin>::proc<0>(f); }\n' % (scale, bq, terms))
open(os.path.join(HERE, 'bnc_table.h'), 'w').write(
    '// generated by gen_models.py: table4 = the weights of bnc_lin.h in a PROGMEM table and a loop\n#include <avr/pgmspace.h>\n#include <stdint.h>\n'
    'static const int8_t BNC_W[4] PROGMEM = {%s};\n'
    '__attribute__((noinline)) bool bnc_predict(const uint8_t* x){ int32_t a=%d; for(uint8_t i=0;i<4;i++) a+=int16_t((int8_t)pgm_read_byte(&BNC_W[i]))*int16_t(x[i]); return a>0; }\n'
    % (','.join(str(v) for v in wq), bq))

# ---- emlearn trees: inline, float features (the default) and uint8_t features
os.makedirs(os.path.join(HERE, 'models'), exist_ok=True)
for d in TREE_DEPTHS:
    for tag, dtype in (('f32', 'float'), ('u8', 'uint8_t')):
        accs, nodes = [], None
        for f in range(NFOLD):
            Xtr, ytr, Xte, yte = folds[f]
            clf = DecisionTreeClassifier(max_depth=d, random_state=0).fit(Xtr, ytr)
            c = emlearn.convert(clf, method='inline', dtype=dtype)
            pred = c.predict(Xte.astype(np.float32 if dtype == 'float' else np.uint8))
            accs.append(float((pred == yte).mean()))
            if f == 1:
                nodes = int(clf.tree_.node_count)
                name = 'tree_d%d_%s' % (d, tag)
                code = c.save(name=name)
                call = ('float v[4]={(float)x[0],(float)x[1],(float)x[2],(float)x[3]}; return %s_predict(v,4);' % name) if dtype == 'float' \
                    else 'return %s_predict(x,4);' % name
                open(os.path.join(HERE, 'models', 'eml_%s.h' % name), 'w').write(
                    '// generated by gen_models.py: emlearn %s inline decision tree, depth %d, %s features (fold 1; %d nodes)\n#include <stdint.h>\n%s\n'
                    '__attribute__((noinline)) bool bnc_predict(const uint8_t* x){ %s }\n' % (results['emlearn'], d, dtype, nodes, code, call))
        record('eml_tree_d%d_%s' % (d, tag), accs, nodes=nodes, depth=d, features=dtype)

# ---- emlearn MLPs (eml_net): one hidden layer, relu; inputs x/255 folded into layer 0 so the device feeds the raw byte values
for h in MLP_HIDDEN:
    accs, params = [], None
    for f in range(NFOLD):
        Xtr, ytr, Xte, yte = folds[f]
        # 5 random restarts, the best on the TRAINING rows kept (the wave search of bn2.c also restarts 4 times): a 2-unit relu net often dies on one start
        fits = [MLPClassifier(hidden_layer_sizes=(h,), activation='relu', solver='adam', max_iter=3000, random_state=seed).fit(Xtr / 255.0, ytr) for seed in range(5)]
        mlp = max(fits, key=lambda m: m.score(Xtr / 255.0, ytr))
        mlp.coefs_[0] = mlp.coefs_[0] / 255.0                       # now the network takes 0..255 directly, same function
        c = emlearn.convert(mlp, method='loadable')
        pred = c.predict(Xte.astype(np.float32))
        accs.append(float((pred == yte).mean()))
        if f == 1:
            params = int(sum(w.size for w in mlp.coefs_) + sum(b.size for b in mlp.intercepts_))
            name = 'mlp_h%d' % h
            code = c.save(name=name)
            open(os.path.join(HERE, 'models', 'eml_%s.h' % name), 'w').write(
                '// generated by gen_models.py: emlearn eml_net MLP 4-%d-1, relu/logistic, float (fold 1; %d parameters)\n%s\n'
                '__attribute__((noinline)) bool bnc_predict(const uint8_t* x){ float v[4]={(float)x[0],(float)x[1],(float)x[2],(float)x[3]}; return %s_predict(v,4); }\n'
                % (h, params, code, name))
    record('eml_mlp_h%d' % h, accs, hidden=h, parameters=params)

json.dump(results, open(os.path.join(HERE, 'results.json'), 'w'), indent=1)
print('%-16s %s' % ('model', 'test accuracy per fold (%), mean'))
for k, v in results['models'].items():
    print('%-16s %s  mean %.2f' % (k, v['test_acc_per_fold'], v['test_acc_mean']))
