// generated by gen_models.py: emlearn eml_net MLP 4-4-1, relu/logistic, float (fold 1; 25 parameters)

#include <eml_net.h>
static const float mlp_h4_layer_0_biases[4] = { 1.225809f, 2.190268f, -1.463762f, 2.637587f };
static const float mlp_h4_layer_0_weights[16] = { -0.010170f, -0.004334f, 0.010269f, -0.005164f, -0.004370f, -0.005044f, 0.009166f, -0.003516f, 0.002903f, -0.012197f, 0.011359f, -0.011130f, 0.003593f, 0.002649f, -0.002740f, -0.000658f };
static const float mlp_h4_layer_1_biases[1] = { 0.298724f };
static const float mlp_h4_layer_1_weights[4] = { 5.190738f, 3.148800f, -3.642385f, 3.736418f };
static float mlp_h4_buf1[4];
static float mlp_h4_buf2[4];
static const EmlNetLayer mlp_h4_layers[2] = { 
{ 4, 4, mlp_h4_layer_0_weights, mlp_h4_layer_0_biases, EmlNetActivationRelu }, 
{ 1, 4, mlp_h4_layer_1_weights, mlp_h4_layer_1_biases, EmlNetActivationLogistic } };
static EmlNet mlp_h4 = { 2, mlp_h4_layers, mlp_h4_buf1, mlp_h4_buf2, 4 };

    int32_t
    mlp_h4_predict(const float *features, int32_t n_features)
    {
        return eml_net_predict(&mlp_h4, features, n_features);
    }
    

    int32_t
    mlp_h4_regress(const float *features, int32_t n_features, float *out, int32_t out_length)
    {
        return eml_net_regress(&mlp_h4, features, n_features, out, out_length);
    }
    

    float
    mlp_h4_regress1(const float *features, int32_t n_features)
    {
        return eml_net_regress1(&mlp_h4, features, n_features);
    }
    
__attribute__((noinline)) bool bnc_predict(const uint8_t* x){ float v[4]={(float)x[0],(float)x[1],(float)x[2],(float)x[3]}; return mlp_h4_predict(v,4); }
