// generated by gen_models.py: emlearn 0.23.2 inline decision tree, depth 6, uint8_t features (fold 1; 45 nodes)
#include <stdint.h>



    // !!! This file is generated using emlearn !!!

    #include <stdint.h>
    

static inline int32_t tree_d6_u8_tree_0(const uint8_t *features, int32_t features_length) {
          if (features[0] < 135) {
              if (features[1] < 205) {
                  if (features[0] < 120) {
                      if (features[2] < 125) {
                          return 1;
                      } else {
                          if (features[1] < 111) {
                              return 1;
                          } else {
                              return 0;
                          }
                      }
                  } else {
                      if (features[2] < 61) {
                          if (features[1] < 190) {
                              return 1;
                          } else {
                              return 0;
                          }
                      } else {
                          if (features[3] < 223) {
                              if (features[0] < 131) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          } else {
                              if (features[1] < 125) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          }
                      }
                  }
              } else {
                  if (features[0] < 42) {
                      return 1;
                  } else {
                      return 0;
                  }
              }
          } else {
              if (features[2] < 9) {
                  if (features[1] < 202) {
                      return 1;
                  } else {
                      return 0;
                  }
              } else {
                  if (features[0] < 159) {
                      if (features[2] < 33) {
                          if (features[1] < 187) {
                              return 1;
                          } else {
                              return 0;
                          }
                      } else {
                          if (features[3] < 218) {
                              if (features[3] < 206) {
                                  return 0;
                              } else {
                                  return 0;
                              }
                          } else {
                              if (features[2] < 86) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          }
                      }
                  } else {
                      if (features[0] < 167) {
                          if (features[2] < 29) {
                              if (features[1] < 195) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          } else {
                              return 0;
                          }
                      } else {
                          return 0;
                      }
                  }
              }
          }
        }
        

int32_t tree_d6_u8_predict(const uint8_t *features, int32_t features_length) {

        int32_t votes[2] = {0,};
        int32_t _class = -1;

        _class = tree_d6_u8_tree_0(features, features_length); votes[_class] += 1;
    
        int32_t most_voted_class = -1;
        int32_t most_voted_votes = 0;
        for (int32_t i=0; i<2; i++) {

            if (votes[i] > most_voted_votes) {
                most_voted_class = i;
                most_voted_votes = votes[i];
            }
        }
        return most_voted_class;
    }
    

int tree_d6_u8_predict_proba(const uint8_t *features, int32_t features_length, float *out, int out_length) {

        int32_t _class = -1;

        for (int i=0; i<out_length; i++) {
            out[i] = 0.0f;
        }

        _class = tree_d6_u8_tree_0(features, features_length); out[_class] += 1.0f;
    
        // compute mean
        for (int i=0; i<out_length; i++) {
            out[i] = out[i] / 1;
        }
        return 0;
    }
    
__attribute__((noinline)) bool bnc_predict(const uint8_t* x){ return tree_d6_u8_predict(x,4); }
