// generated by gen_models.py: emlearn eml_net MLP 4-8-1, relu/logistic, float (fold 1; 49 parameters)

#include <eml_net.h>
static const float mlp_h8_layer_0_biases[8] = { 2.123486f, -0.023943f, 1.371016f, -0.159958f, 2.574500f, 2.133831f, -0.477582f, 0.463112f };
static const float mlp_h8_layer_0_weights[32] = { -0.005840f, -0.000000f, -0.010096f, -0.000000f, -0.006855f, -0.005420f, -0.000000f, 0.000568f, -0.005694f, -0.000000f, -0.003404f, -0.000000f, -0.006886f, -0.005509f, -0.000000f, -0.001169f, -0.007870f, -0.000000f, 0.002789f, -0.000000f, -0.010225f, -0.011398f, 0.000000f, -0.007040f, 0.001421f, 0.000000f, 0.000651f, -0.000000f, 0.001781f, 0.001844f, 0.000000f, -0.000684f };
static const float mlp_h8_layer_1_biases[1] = { -4.175087f };
static const float mlp_h8_layer_1_weights[8] = { 5.117443f, 0.000000f, 5.642669f, -0.000000f, 4.317777f, 4.795284f, -0.000000f, 1.121142f };
static float mlp_h8_buf1[8];
static float mlp_h8_buf2[8];
static const EmlNetLayer mlp_h8_layers[2] = { 
{ 8, 4, mlp_h8_layer_0_weights, mlp_h8_layer_0_biases, EmlNetActivationRelu }, 
{ 1, 8, mlp_h8_layer_1_weights, mlp_h8_layer_1_biases, EmlNetActivationLogistic } };
static EmlNet mlp_h8 = { 2, mlp_h8_layers, mlp_h8_buf1, mlp_h8_buf2, 8 };

    int32_t
    mlp_h8_predict(const float *features, int32_t n_features)
    {
        return eml_net_predict(&mlp_h8, features, n_features);
    }
    

    int32_t
    mlp_h8_regress(const float *features, int32_t n_features, float *out, int32_t out_length)
    {
        return eml_net_regress(&mlp_h8, features, n_features, out, out_length);
    }
    

    float
    mlp_h8_regress1(const float *features, int32_t n_features)
    {
        return eml_net_regress1(&mlp_h8, features, n_features);
    }
    
__attribute__((noinline)) bool bnc_predict(const uint8_t* x){ float v[4]={(float)x[0],(float)x[1],(float)x[2],(float)x[3]}; return mlp_h8_predict(v,4); }
