// generated by gen_models.py: emlearn eml_net MLP 4-16-1, relu/logistic, float (fold 1; 97 parameters)

#include <eml_net.h>
static const float mlp_h16_layer_0_biases[16] = { -0.493001f, -0.035584f, 2.010720f, -0.001768f, -0.362418f, 1.712484f, 0.377118f, -0.397127f, 0.206620f, -1.059103f, -0.112089f, 0.444200f, 1.148881f, -1.530622f, 2.149107f, -0.599350f };
static const float mlp_h16_layer_0_weights[64] = { 0.000000f, 0.000687f, -0.006329f, -0.000000f, 0.002394f, -0.006751f, -0.001502f, 0.000000f, -0.005333f, 0.002888f, -0.000000f, -0.005890f, -0.001131f, 0.007212f, -0.007748f, 0.004765f, 0.000000f, -0.000046f, -0.003516f, 0.000000f, 0.005236f, -0.001760f, -0.001076f, 0.000000f, -0.006797f, 0.005010f, -0.000000f, -0.006172f, -0.002552f, 0.006618f, -0.004138f, 0.003661f, 0.000000f, -0.000132f, -0.006304f, -0.000000f, 0.009271f, -0.005781f, -0.002250f, -0.000000f, 0.009179f, 0.011739f, -0.000000f, 0.002399f, -0.005851f, 0.009824f, -0.007644f, 0.007491f, 0.000000f, -0.001755f, 0.001169f, 0.000000f, -0.000792f, 0.001730f, -0.000217f, -0.000000f, 0.001920f, -0.001678f, -0.000000f, 0.005483f, -0.000031f, -0.000750f, 0.003375f, 0.000053f };
static const float mlp_h16_layer_1_biases[1] = { 0.931379f };
static const float mlp_h16_layer_1_weights[16] = { 0.000000f, 0.095044f, 3.201925f, 0.000000f, -1.619562f, 3.063088f, -0.043916f, 0.000000f, 3.948539f, -2.076019f, -0.000000f, 3.406387f, 2.220839f, -2.250230f, 2.576742f, -1.821965f };
static float mlp_h16_buf1[16];
static float mlp_h16_buf2[16];
static const EmlNetLayer mlp_h16_layers[2] = { 
{ 16, 4, mlp_h16_layer_0_weights, mlp_h16_layer_0_biases, EmlNetActivationRelu }, 
{ 1, 16, mlp_h16_layer_1_weights, mlp_h16_layer_1_biases, EmlNetActivationLogistic } };
static EmlNet mlp_h16 = { 2, mlp_h16_layers, mlp_h16_buf1, mlp_h16_buf2, 16 };

    int32_t
    mlp_h16_predict(const float *features, int32_t n_features)
    {
        return eml_net_predict(&mlp_h16, features, n_features);
    }
    

    int32_t
    mlp_h16_regress(const float *features, int32_t n_features, float *out, int32_t out_length)
    {
        return eml_net_regress(&mlp_h16, features, n_features, out, out_length);
    }
    

    float
    mlp_h16_regress1(const float *features, int32_t n_features)
    {
        return eml_net_regress1(&mlp_h16, features, n_features);
    }
    
__attribute__((noinline)) bool bnc_predict(const uint8_t* x){ float v[4]={(float)x[0],(float)x[1],(float)x[2],(float)x[3]}; return mlp_h16_predict(v,4); }
