// generated by gen_models.py: emlearn eml_net MLP 4-2-1, relu/logistic, float (fold 1; 13 parameters)

#include <eml_net.h>
static const float mlp_h2_layer_0_biases[2] = { 2.862380f, -2.856635f };
static const float mlp_h2_layer_0_weights[8] = { -0.007428f, 0.014195f, -0.005986f, 0.010795f, -0.009248f, 0.010736f, 0.001828f, -0.001520f };
static const float mlp_h2_layer_1_biases[1] = { 1.313497f };
static const float mlp_h2_layer_1_weights[2] = { 4.249354f, -3.887036f };
static float mlp_h2_buf1[4];
static float mlp_h2_buf2[4];
static const EmlNetLayer mlp_h2_layers[2] = { 
{ 2, 4, mlp_h2_layer_0_weights, mlp_h2_layer_0_biases, EmlNetActivationRelu }, 
{ 1, 2, mlp_h2_layer_1_weights, mlp_h2_layer_1_biases, EmlNetActivationLogistic } };
static EmlNet mlp_h2 = { 2, mlp_h2_layers, mlp_h2_buf1, mlp_h2_buf2, 4 };

    int32_t
    mlp_h2_predict(const float *features, int32_t n_features)
    {
        return eml_net_predict(&mlp_h2, features, n_features);
    }
    

    int32_t
    mlp_h2_regress(const float *features, int32_t n_features, float *out, int32_t out_length)
    {
        return eml_net_regress(&mlp_h2, features, n_features, out, out_length);
    }
    

    float
    mlp_h2_regress1(const float *features, int32_t n_features)
    {
        return eml_net_regress1(&mlp_h2, features, n_features);
    }
    
__attribute__((noinline)) bool bnc_predict(const uint8_t* x){ float v[4]={(float)x[0],(float)x[1],(float)x[2],(float)x[3]}; return mlp_h2_predict(v,4); }
