// generated by gen_models.py: emlearn 0.23.2 inline decision tree, depth 8, float features (fold 1; 57 nodes)
#include <stdint.h>



    // !!! This file is generated using emlearn !!!

    #include <stdint.h>
    

static inline int32_t tree_d8_f32_tree_0(const float *features, int32_t features_length) {
          if (features[0] < 135.500000f) {
              if (features[1] < 205.500000f) {
                  if (features[0] < 120.500000f) {
                      if (features[2] < 125.500000f) {
                          return 1;
                      } else {
                          if (features[1] < 111.000000f) {
                              return 1;
                          } else {
                              return 0;
                          }
                      }
                  } else {
                      if (features[2] < 61.500000f) {
                          if (features[1] < 190.000000f) {
                              return 1;
                          } else {
                              return 0;
                          }
                      } else {
                          if (features[3] < 223.500000f) {
                              if (features[0] < 131.000000f) {
                                  if (features[3] < 220.000000f) {
                                      return 0;
                                  } else {
                                      if (features[2] < 107.500000f) {
                                          return 1;
                                      } else {
                                          return 0;
                                      }
                                  }
                              } else {
                                  if (features[1] < 160.500000f) {
                                      return 1;
                                  } else {
                                      return 0;
                                  }
                              }
                          } else {
                              if (features[1] < 125.500000f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          }
                      }
                  }
              } else {
                  if (features[0] < 42.500000f) {
                      return 1;
                  } else {
                      return 0;
                  }
              }
          } else {
              if (features[2] < 9.500000f) {
                  if (features[0] < 190.000000f) {
                      return 1;
                  } else {
                      return 0;
                  }
              } else {
                  if (features[0] < 159.500000f) {
                      if (features[2] < 33.500000f) {
                          if (features[1] < 187.000000f) {
                              return 1;
                          } else {
                              return 0;
                          }
                      } else {
                          if (features[3] < 218.500000f) {
                              if (features[3] < 206.000000f) {
                                  if (features[0] < 138.000000f) {
                                      if (features[2] < 48.000000f) {
                                          return 1;
                                      } else {
                                          return 0;
                                      }
                                  } else {
                                      return 0;
                                  }
                              } else {
                                  if (features[2] < 61.500000f) {
                                      return 1;
                                  } else {
                                      return 0;
                                  }
                              }
                          } else {
                              if (features[2] < 86.000000f) {
                                  return 1;
                              } else {
                                  return 0;
                              }
                          }
                      }
                  } else {
                      if (features[0] < 167.500000f) {
                          if (features[2] < 29.000000f) {
                              if (features[3] < 161.000000f) {
                                  return 0;
                              } else {
                                  return 1;
                              }
                          } else {
                              return 0;
                          }
                      } else {
                          return 0;
                      }
                  }
              }
          }
        }
        

int32_t tree_d8_f32_predict(const float *features, int32_t features_length) {

        int32_t votes[2] = {0,};
        int32_t _class = -1;

        _class = tree_d8_f32_tree_0(features, features_length); votes[_class] += 1;
    
        int32_t most_voted_class = -1;
        int32_t most_voted_votes = 0;
        for (int32_t i=0; i<2; i++) {

            if (votes[i] > most_voted_votes) {
                most_voted_class = i;
                most_voted_votes = votes[i];
            }
        }
        return most_voted_class;
    }
    

int tree_d8_f32_predict_proba(const float *features, int32_t features_length, float *out, int out_length) {

        int32_t _class = -1;

        for (int i=0; i<out_length; i++) {
            out[i] = 0.0f;
        }

        _class = tree_d8_f32_tree_0(features, features_length); out[_class] += 1.0f;
    
        // compute mean
        for (int i=0; i<out_length; i++) {
            out[i] = out[i] / 1;
        }
        return 0;
    }
    
__attribute__((noinline)) bool bnc_predict(const uint8_t* x){ float v[4]={(float)x[0],(float)x[1],(float)x[2],(float)x[3]}; return tree_d8_f32_predict(v,4); }
